name: Content Generation and Deployment

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: gh-pages # Specify the 'gh-pages' branch
          token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x" # Specify the Python version

      - name: Install Python dependencies
        run: pip install openai # Installs the OpenAI package

      - name: Run Content Generation Script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} # Set the environment variable
        run: |
          python content-generation-script.py

      - name: Upload New Files and Updated Topics as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: generated-content
          path: |
            _blahbly/
            topics.txt

      - name: Commit
        run: |
          git config --global user.name 'christianengineer'
          git config --global user.email 'christian.ipanaque@engineer.com'
          git add .
          git commit -m "Automated content update"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
          branch: gh-pages
